=== andyroode/DevOpsLearning/schemas/paramset.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "name" : { "type": "string" },
        "version" : { "type": "number" },
        "parameters" : { "type": "object" },
        "applications": {
            "type" :"array",
            "items": {
                "type": "object",
                "properties": {
                    "appName": { "type": "string"},
                    "parameters" : { "type": "object" }
                }
            }
        }
    },
    "required": ["name", "parameters"]
}

=== andyroode/DevOpsLearning/test_data/test_templates/parameters/composite-sample/data-management-tech.json
{
  "name" : "data-management-tech",
  "version" : 23.1,
  "parameters" : {
    "BSS_NAMESPACE" : "${NAMESPACE.replaceFirst(/-data-management$/, \"-bss\")}",
    "OSS_NAMESPACE" : "${NAMESPACE.replaceFirst(/-data-management$/, \"-oss\")}"
  },
  "applications" : [ {
    "parameters" : {
      "beoc_package.CPQ_NAMESPACE" : "${BSS_NAMESPACE}",
      "beoc_package.CIM_NAMESPACE" : "${BSS_NAMESPACE}",
      "beoc_package.COM_NAMESPACE" : "${BSS_NAMESPACE}"
    },
    "appName" : "beoc"
  }, {
    "parameters" : {
      "dpt_package.COM_NAMESPACE" : "${BSS_NAMESPACE}",
      "dpt_package.CLOUD_NAME" : "${CLOUD_PUBLIC_HOST}",
      "dpt_package.NAMESPACE" : "${NAMESPACE}",
      "dpt_package.ESO_NAMESPACE" : "${OSS_NAMESPACE}"
    },
    "appName" : "dpt"
  }, {
    "parameters" : {
      "dpt_package.CLOUD_NAME" : "${CLOUD_PUBLIC_HOST}"
    },
    "appName" : "ftpd-dpt-configuration-sample"
  } ]
}

=== andyroode/DevOpsLearning/test_data/test_templates/parameters/composite-sample/oss.json
{
  "name" : "oss",
  "version" : 23.1,
  "parameters" : {
    "DM_NAMESPACE" : "${NAMESPACE.replaceFirst(/-(\\w)*$/, \"-data-management\")}",
    "MUI_SKIP_FRAGMENT_DEPLOY_CHECK" : "true",
    "NETWORK_ADAPTERS_NAMESPACE" : "${NAMESPACE.replaceFirst(/-(\\w)*$/, \"-network-adapters\")}",
    "BSS_NAMESPACE" : "${NAMESPACE.replaceFirst(/-(\\w)*$/, \"-bss\")}",
    "STRUCTURED_GLOBAL_RESOURCE_PROFILE" : {
      "ftpd_dev" : {
        "content-delivery-manager" : {
          "CPU_REQUEST" : "50m",
          "MEMORY_REQUEST" : "75Mi",
          "CPU_LIMIT" : "1",
          "#inherit" : "dev_az11",
          "MEMORY_LIMIT" : "75Mi"
        },
        "frontend-gateway" : {
          "INTERNAL_GW_MEMORY_REQUEST" : "200Mi",
          "INTERNAL_GW_CPU_LIMIT" : "500m",
          "PRIVATE_GW_MEMORY_REQUEST" : "100Mi",
          "INTERNAL_GW_MEMORY_LIMIT" : "200Mi",
          "PRIVATE_GW_CPU_LIMIT" : "100m",
          "PRIVATE_GW_MEMORY_LIMIT" : "100Mi",
          "CPU_REQUEST" : "30m",
          "#inherit" : "dev_az11"
        },
        "facade-operator" : {
          "FACADE_GATEWAY_MEMORY_LIMIT" : "96Mi",
          "#inherit" : "dev",
          "_comment" : "This memory limit only applies to those gateways whose service does not have an explicitly defined FacadeService. If the service has an explicitly defined FacadeService, then the parameter COMPOSITE_GATEWAY_MEMORY_LIMIT must be passed to this service."
        },
        "tenant-manager" : {
          "CPU_REQUEST" : "30m",
          "MEMORY_REQUEST" : "500Mi",
          "CPU_LIMIT" : "1500m",
          "#inherit" : "dev_az11",
          "MEMORY_LIMIT" : "500Mi"
        },
        "tenant-self-service-frontend" : {
          "#inherit" : "dev_az11",
          "MEMORY_LIMIT" : "64Mi"
        },
        "paas-mediation" : {
          "#inherit" : "dev",
          "MEMORY_LIMIT" : "100Mi"
        },
        "dumps-cleanup-service" : {
          "DUMPS_CLEANUP_SERVICE_MEMORY_REQUEST" : "100Mi",
          "DUMPS_CLEANUP_SERVICE_CPU_LIMIT" : "100m",
          "DUMPS_CLEANUP_SERVICE_CPU_REQUEST" : "20m",
          "#inherit" : "dev_az11",
          "DUMPS_CLEANUP_SERVICE_MEMORY_LIMIT" : "150Mi"
        },
        "access-control" : {
          "#inherit" : "dev",
          "MEMORY_LIMIT" : "550Mi",
          "MEMORY_REQUEST" : "550Mi"
        }
      }
    },
    "GLOBAL_RESOURCE_PROFILE" : "${STRUCTURED_GLOBAL_RESOURCE_PROFILE}"
  },
  "applications" : [ {
    "parameters" : {
      "COMPOSITE_PLATFORM" : "true"
    },
    "appName" : "Cloud-Core"
  }, {
    "parameters" : {
      "USE_POSTGRESQL_AS_DB" : "true",
      "UUI_INITIAL_APP" : "uui/number-management",
      "MONITORING_ENABLED" : "true",
      "EXTERNAL_ROUTES_PROTOCOL" : "https",
      "SUPERSET_EXTERNAL_URL" : "${EXTERNAL_ROUTES_PROTOCOL}://reporting-superset-ext-${DM_NAMESPACE}.${CLOUD_PUBLIC_HOST}"
    },
    "appName" : "oss.common.umbrella-ui"
  }, {
    "parameters" : {
      "DUMPS_MONGODB_NAME" : "${NAMESPACE.replace(\"-\",\"_\")}_dumps",
      "MISTRAL_PROJECT" : "http://wiremock-server-wiremock.svc:8080",
      "--PARAMETERS_MISSING_IN_NOTES--" : "=====================",
      "NE_MONGO_DB_NAME" : "${NAMESPACE.replace(\"-\",\"_\")}_ne"
    },
    "appName" : "oss.common.utils"
  }, {
    "parameters" : {
      "RENDERER_ENVIRONMENT" : "API_GATEWAY_URL = http://internal-gateway-service:8080; ESO_MANAGER_URL = http://eso-manager:8080; SERVICE_REQUESTS_URL = http://service-requests:8080; USER_TASK_MANAGER_URL = http://user-task-manager:8080; MONITORING_CONSOLE_URL = http://monitoring-console:8080; NDO_API_GATEWAY_URL = http://internal-gateway-service:8080; CM_GATEWAY_URL = http://cm-gateway:8080; SERVICE_MANAGER_URL = http://service-manager:8080; NDO_PATH_COMPUTATION_ENGINE_URL = http://path-computation-engine:8080; AM_URL = http://allocation-manager:8080",
      "ZOOKEEPER_URL" : "${tenant.cloud.ZOOKEEPER_ADDRESS}",
      "INTEGRATION_LOGS_TOPIC" : "${NAMESPACE}_logs"
    },
    "appName" : "oss.orchestration.core"
  }, {
    "parameters" : {
      "CAPACITY_MANAGEMENT_DATASOURCE" : "datamart-builder",
      "KAFKA_SECURITY_ENABLED" : "${tenant.cloud.CLOUD_KAFKA_SECURITY_ENABLED}",
      "MONITORING_ENABLED" : "true",
      "REPORTING_POSTGRES_DB_NOSUPER_READ_ONLY_USERNAME" : "${NAMESPACE}_reporting_read_only_user",
      "REPORTING_POSTGRES_DB_NOSUPER_PASSWORD" : "${POSTGRES_DB_PASSWORD}",
      "DB_POSTGRES_DB_NAME" : "${NAMESPACE.replace(\"-\",\"_\")}_reporting",
      "CDI_REPORTING_POSTGRES_DB_NAME" : "${NAMESPACE.replace(\"-\",\"_\")}_cdi_reporting",
      "SPR_KAFKA_APPLICATION_ID" : "${NAMESPACE}_sink-processor-reporting",
      "--PARAMETERS_MISSING_IN_NOTES--" : "=====================",
      "REPORTING_POSTGRES_DB_NOSUPER_USERNAME" : "${POSTGRES_DB_USERNAME}"
    },
    "appName" : "platform.reporting"
  }, {
    "parameters" : {
      "--PARAMETERS_MISSING_IN_NOTES--" : "=====================",
      "DB_NAME_PREFIX" : "${NAMESPACE.replace(\"-\",\"_\")}",
      "MONITORING_ENABLED" : "true"
    },
    "appName" : "resource-inventory.ip-address-management"
  }, {
    "parameters" : {
      "IDP_TENANT" : "${tenant.cloud.DEFAULT_TENANT_NAME}",
      "KAFKA_SECURITY_ENABLED" : "${tenant.cloud.CLOUD_KAFKA_SECURITY_ENABLED}",
      "DB_NAME_PREFIX" : "${NAMESPACE.replace(\"-\",\"_\")}",
      "MONITORING_ENABLED" : "true",
      "####IDP_TOKEN_URL" : "http://identity-provider:8080/auth/realms/${IDP_TENANT}/protocol/openid-connect/token"
    },
    "appName" : "resource-inventory.phone-book"
  }, {
    "parameters" : {
      "KAFKA_SECURITY_ENABLED" : "${tenant.cloud.CLOUD_KAFKA_SECURITY_ENABLED}",
      "SIM_PROFILE_MANAGER_RELEASE_SCHEDULE_ENABLED" : "false",
      "DB_NAME_PREFIX" : "${NAMESPACE.replace(\"-\",\"_\")}"
    },
    "appName" : "resource-inventory.sim-management"
  } ]
}

=== andyroode/DevOpsLearning/test_data/test_environments/sample-cloud-name/composite-with-env-specific/Inventory/parameters/env-specific-bss.json
{
	"name": "env-specific-bss",
	"version": 23.1,
	"parameters": {
		"OVERRIDE_PARAMETER": "env-specific-value"
	},
	"applications": [
		{
			"appName": "PROJECT-NOTIFICATION",
			"parameters": {
				"CPQ_QUOTE_NOTIFICATION_TOPIC": "DV.Customer.QuoteManagement.Quote",
        		"PROJECT_IBS_NOTIFICATION_SERVICE_TOPIC" : "DV.Product.ProductInventory.Product",
        		"OM_PROJECT_ORDER_NOTIFICATION_TOPIC" : "DV.Customer.ProductOrdering.ProductOrder"
			}	
		}
	]
}

=== andyroode/DevOpsLearning/test_data/test_environments/parameters/prod-shared.json
{
	"name": "prod-shared",
	"version": 23.1,
	"parameters": {},
	"applications": [
		{
			"appName": "TELUS-NOTIFICATION",
			"parameters": {
				"CPQ_QUOTE_NOTIFICATION_TOPIC": "DV.Customer.QuoteManagement.Quote",
        		"TELUS_IBS_NOTIFICATION_SERVICE_TOPIC" : "DV.Product.ProductInventory.Product",
        		"OM_TELUS_ORDER_NOTIFICATION_TOPIC" : "DV.Customer.ProductOrdering.ProductOrder"
			}	
		}
	]
}

=== andyroode/DevOpsLearning/test_data/test_templates/parameters/composite-sample/bss.json
{
  "version" : 1,
  "name" : "bss",
  "parameters" : {
    "BILLING_NAMESPACE" : "${NAMESPACE.replaceFirst(/-(\\w)*$/, \"-billing\")}",
    "OSS_NAMESPACE" : "${NAMESPACE.replaceFirst(/-(\\w)*$/, \"-oss\")}"
  },
  "applications" : [ {
    "appName" : "CRM-CIM",
    "parameters" : {
      "UIM_INTEGRATION_ENABLED" : "true",
      "ENTITLEMENTS_ENABLED_CIM" : "true",
      "CIM_CHANGE_NOTIFICATIONS_ENABLED" : "true",
      "BSS_INTEGRATION_UIM_ENABLED" : "true"
    }
  }, {
    "appName" : "Cloud-Workplaces-FRW-Runtime",
    "parameters" : {
      "WP_RUNTIME_ON_START_LOAD" : "true",
      "WP_RUNTIME_MODE" : "CACHE"
    }
  }, {
    "appName" : "CloudBSS-CPM",
    "parameters" : {
      "IMWS_EMAIL_PASSWORD" : "${SMTP_SERVER_PASSWORD}",
      "ZOOKEEPER_ENABLED" : "true",
      "IMWS_EMAIL_USERNAME" : "${SMTP_SERVER_USERNAME}",
      "IMWS_EMAIL_SERVER_URL" : "${tenant.cloud.SMTP_SERVER_URL}"
    }
  }, {
    "appName" : "CloudBSS-CPMCIP",
    "parameters" : {
      "BSS_INTEGRATION_NRM_MODE" : "composite",
      "BSS_INTEGRATION_NRM_DOMAIN" : "${BILLING_NAMESPACE}",
      "bss.integration.nrm.eca2-url" : "eca2.${BILLING_NAMESPACE}:8080",
      "bss.integration.nrm.rtb-url" : "realtime-bills.${BILLING_NAMESPACE}:8080"
    }
  }, {
    "appName" : "CloudBSS-CPQBE",
    "parameters" : {
      "ENTITLEMENTS_ENABLED_IBS" : "true"
    }
  }, {
    "appName" : "CloudBSS-MCBE",
    "parameters" : {
      "CH_CMS_ADAPTER" : "contentful"
    }
  }, {
    "appName" : "CloudBSS-SPS",
    "parameters" : {
      "STORAGE_ENDPOINT" : "${tenant.cloud.STORAGE_SERVER_URL}",
      "STORAGE_SECRET_KEY" : "${STORAGE_PASSWORD}",
      "STORAGE_TEMPORARY_BUCKET_NAME" : "${tenant.cloud.DOC_STORAGE_TEMPORARY_BUCKET_NAME}",
      "STORAGE_PERSISTENT_BUCKET_NAME" : "${tenant.cloud.DOC_STORAGE_PERSISTENT_BUCKET_NAME}",
      "STORAGE_ACCESS_KEY" : "${STORAGE_USERNAME}"
    }
  }, {
    "appName" : "CloudCRM-CBM",
    "parameters" : {
      "ECA2_LOGS" : "true",
      "BSS_INTEGRATION_NRM_MODE" : "composite",
      "BSS_INTEGRATION_NRM_DOMAIN" : "${BILLING_NAMESPACE}"
    }
  }, {
    "appName" : "CloudCRM-GraphQL",
    "parameters" : {
      "BSS_INTEGRATION_NRM_MODE" : "composite",
      "BSS_INTEGRATION_NRM_DOMAIN" : "${BILLING_NAMESPACE}"
    }
  }, {
    "appName" : "CloudMigrationNiFi",
    "parameters" : {
      "NIFI_USE_TLS_PASSTHROUGH_INGRESS" : "true",
      "NIFI_EXPOSE_CUSTOM_PORTS" : "upload_8081,prepare-data_8083,diagnostic_8084,webhooks_32080,cdc-monitor_9194,dst-export_8056,dst-import_8057,cdm-monitor_9192",
      "NIFI_PV_STORAGE_CLASS" : "${tenant.cloud.STORAGE_RWO_CLASS}",
      "NIFI_CUSTOM_MONITORING_PORTS" : "cdc-monitor_30s,cdm-monitor_15s"
    }
  }, {
    "appName" : "cloud-user-task-manager",
    "parameters" : {
      "KAFKA_SECURITY_ENABLED" : "true"
    }
  }, {
    "appName" : "cloudbss-om",
    "parameters" : {
      "OM_CLEANUP_POLLING_INTERVAL" : "40000",
      "OM_ESO_CALLBACK_URL" : "http://cloud-integration-platform-engine.${NAMESPACE}:8080/routes",
      "OM_ESO_SERVICE_REQUESTS_URL" : "http://service-requests.${OSS_NAMESPACE}:8080",
      "OM_ESO_URL" : "http://eso-manager.${OSS_NAMESPACE}:8080",
      "OM_SPM_IDENTITY_PROVIDER_EXTERNAL" : "false",
      "OM_PB_URL" : "http://phone-book.${OSS_NAMESPACE}.svc.cluster.local:8080",
      "ZOOKEEPER_ENABLED" : "true",
      "OM_PB_RELEASE_VERSION" : "23.1",
      "OM_SPM_RELEASE_VERSION" : "23.1",
      "OM_CIP_DEPLOYED_INTEGRATIONS" : "[\"som\",\"eso\",\"utm\",\"ibs\",\"uim\",\"pb\",\"spm\"]",
      "OM_SPM_URL" : "http://sim-profile-manager.${OSS_NAMESPACE}.svc.cluster.local:8080",
      "OM_PB_IDENTITY_PROVIDER_EXTERNAL" : "false",
      "OM_UIM_URL" : "http://internal-gateway-service:8080",
      "OM_UIM_CRED" : "${creds.get('om-uim-cred').secret}"
    }
  }, {
    "appName" : "uim",
    "parameters" : {
      "UIM_PLUGINS_CONFIGS" : "'{\n  \"plugins\": {\n    \"deliveryPlugins\": [\n      {\n        \"defaultPluginConfig\": {\n          \"pluginSpecificConfigs\": {\n            \"host\": \"${SMPP_HOST}\",\n            \"password\": \"${SMPP_PASSWORD}\",\n            \"port\": \"${SMPP_PORT}\",\n            \"reconnect.interval.millis\": \"30000\",\n            \"submit.timeout\": \"10000\",\n            \"system.id\": \"${SMPP_USERNAME}\",\n            \"window\": \"1\"\n          }\n        },\n        \"implementationConfig\": {\n          \"oobPluginReference\": \"SMS\"\n        },\n        \"pluginInstanceId\": \"SMS\"\n      },\n      {\n        \"defaultPluginConfig\": {\n          \"pluginSpecificConfigs\": {\n            \"host\": \"${tenant.cloud.SMTP_SERVER_URL}\",\n            \"port\": \"${tenant.cloud.SMTP_SERVER_PORT}\",\n            \"transport_strategy\": \"SMTP\",\n            \"username\": \"${SMTP_SERVER_USERNAME}\",\n            \"password\": \"${SMTP_SERVER_PASSWORD}\"            \n          }\n        },\n        \"implementationConfig\": {\n          \"oobPluginReference\": \"E_MAIL\"\n        },\n        \"pluginInstanceId\": \"E_MAIL\"\n      },\n      {\n        \"pluginInstanceId\": \"MOBILE_PUSH\",\n        \"defaultPluginConfig\": {\n          \"pluginSpecificConfigs\": {\n            \"thread_pool.size\": \"8\"\n          }\n        },\n        \"implementationConfig\": {\n          \"oobPluginReference\": \"MOBILE_PUSH\"\n        }\n      }\n    ]\n  }\n}'",
      "DEPLOY_W_HELM" : "true",
      "UIM_PLUGINS_MAPPING" : "'{\n  \"pluginsMapping\": [\n    {\n      \"filters\": [\n        {\n          \"mediumType\": \"E_MAIL\"\n        },\n        {\n          \"mediumType\": \"CALENDAR_EVENT\"\n        }\n      ],\n      \"pluginInstanceId\": \"E_MAIL\"\n    },\n    {\n      \"filters\": [\n        {\n          \"mediumType\": \"SMS\"\n        }\n      ],\n      \"pluginInstanceId\": \"SMS\"\n    },\n    {\n      \"pluginInstanceId\": \"MOBILE_PUSH\",\n      \"filters\": [\n         {\n           \"mediumType\": \"MOBILE_PUSH\"\n         }\n      ]\n    }\n  ]\n}'"
    }
  } ]
}

=== andyroode/DevOpsLearning/test_data/test_templates/parameters/composite-sample/core.json
{
  "name" : "common",
  "version" : 23.1,
  "parameters" : {
    "GATEWAYS_ALLOWED_ORIGIN" : "*.qubership.org,*.qubership.org:*,*.qubership.cloud:*,*.prj.nu:*,*.np-nuuazure.dk,*.np-nuuazure.dk:*",
    "CONSUL_ENABLED" : "true",
    "GLOBAL_RESOURCE_PROFILE" : "'{\n    \"ftpd_dev\": {\n        \"cloud-integration-platform-systems-catalog\": {\n          \"#inherit\": \"dev_az11\",\n          \"_comment\": \"For egress-gateway-gateway.\",\n          \"EGRESS_GATEWAY_MEMORY\": \"128Mi\"\n        },\n        \"content-delivery-manager\": {\n          \"#inherit\": \"dev_az11\",\n          \"CPU_REQUEST\": \"50m\",\n          \"MEMORY_REQUEST\": \"75Mi\",\n          \"CPU_LIMIT\": \"1\",\n          \"MEMORY_LIMIT\": \"75Mi\"\n        },\n        \"nifi-config-service\": {\n          \"#inherit\": \"dev_az11\",\n          \"CPU_REQUEST\": \"100m\",\n          \"MEMORY_REQUEST\": \"140Mi\",\n          \"CPU_LIMIT\": \"1000m\",\n          \"MEMORY_LIMIT\": \"356Mi\"\n        },\n        \"cpm-core-service\": {\n          \"#inherit\": \"dev\",\n          \"_comment\": \"For project-cpm-gateway.\",\n          \"COMPOSITE_GATEWAY_CPU_REQUEST\": \"100m\",\n          \"COMPOSITE_GATEWAY_MEMORY_REQUEST\": \"35Mi\",\n          \"COMPOSITE_GATEWAY_MEMORY_LIMIT\": \"128Mi\"\n        },\n        \"bss-configuration-service\": {\n          \"#inherit\": \"dev_az11\",\n          \"_comment\": \"For bsscs-composite-gateway.\",\n          \"COMPOSITE_GATEWAY_MEMORY_REQUEST\": \"100Mi\",\n          \"COMPOSITE_GATEWAY_MEMORY_LIMIT\": \"100Mi\"\n        },\n        \"geo-site-core\": {\n          \"#inherit\": \"dev_az11\",\n          \"_comment\": \"For geo-site-core-composite-gateway.\",\n          \"COMPOSITE_GATEWAY_MEMORY_REQUEST\": \"124Mi\",\n          \"COMPOSITE_GATEWAY_MEMORY_LIMIT\": \"124Mi\"\n        },\n        \"cdc-nifi-integrations\": {\n          \"#inherit\": \"dev_az11\",\n          \"CPU_REQUEST\": \"100m\",\n          \"MEMORY_REQUEST\": \"200Mi\",\n          \"CPU_LIMIT\": \"1000m\",\n          \"MEMORY_LIMIT\": \"200Mi\"\n        },\n        \"tenant-manager\": {\n          \"#inherit\": \"dev_az11\",\n          \"CPU_REQUEST\": \"30m\",\n          \"MEMORY_REQUEST\": \"500Mi\",\n          \"CPU_LIMIT\": \"1500m\",\n          \"MEMORY_LIMIT\": \"500Mi\"\n        },\n        \"dumps-cleanup-service\": {\n          \"#inherit\": \"dev_az11\",\n          \"DUMPS_CLEANUP_SERVICE_CPU_REQUEST\": \"20m\",\n          \"DUMPS_CLEANUP_SERVICE_MEMORY_REQUEST\": \"100Mi\",\n          \"DUMPS_CLEANUP_SERVICE_CPU_LIMIT\": \"100m\",\n          \"DUMPS_CLEANUP_SERVICE_MEMORY_LIMIT\": \"150Mi\"\n        },\n        \"frontend-gateway\": {\n          \"#inherit\": \"dev_az11\",\n          \"INTERNAL_GW_MEMORY_LIMIT\": \"200Mi\",\n          \"INTERNAL_GW_MEMORY_REQUEST\": \"200Mi\",\n          \"INTERNAL_GW_CPU_LIMIT\": \"500m\",\n          \"PRIVATE_GW_MEMORY_LIMIT\": \"100Mi\",\n          \"PRIVATE_GW_MEMORY_REQUEST\": \"100Mi\",\n          \"PRIVATE_GW_CPU_LIMIT\": \"100m\",\n          \"CPU_REQUEST\": \"30m\"\n        },\n        \"bss-cloud-portal-proxy\": {\n          \"#inherit\": \"dev_az11\",\n          \"MEMORY_LIMIT\": \"48Mi\"\n        },\n        \"bss-config-manager-frontend\": {\n          \"#inherit\": \"dev_az11\",\n          \"MEMORY_LIMIT\": \"48Mi\",\n          \"MEMORY_REQUEST\": \"48Mi\"\n        },\n        \"project-workplaces-configuration\": {\n          \"#inherit\": \"dev_az11\",\n          \"MEMORY_LIMIT\": \"48Mi\"\n        },\n        \"nifi-config-proxy-service\": {\n          \"#inherit\": \"dev\",\n          \"MEMORY_REQUEST\": \"48Mi\"\n        },\n        \"pim-frontend-srv\": {\n          \"#inherit\": \"dev_az11\",\n          \"MEMORY_LIMIT\": \"48Mi\",\n          \"MEMORY_REQUEST\": \"48Mi\"\n        },\n        \"uim\": {\n          \"#inherit\": \"dev\",\n          \"COMPOSITE_GATEWAY_MEMORY_LIMIT\": \"96Mi\",\n          \"CPU_REQUEST\": \"200m\",\n          \"MEMORY_REQUEST\": \"1254Mi\",\n          \"CPU_LIMIT\": \"1\",\n          \"MEMORY_LIMIT\": \"1254Mi\",\n\t\t  \"PREDEPLOY_MEMORY_LIMIT\" : \"1024Mi\",\n          \"PREDEPLOY_MEMORY_REQUEST\" : \"1024Mi\"\n        },\n        \"access-control\": {\n          \"#inherit\": \"dev\",\n          \"MEMORY_REQUEST\": \"550Mi\",\n          \"MEMORY_LIMIT\": \"550Mi\"\n        },\n        \"facade-operator\": {\n          \"#inherit\": \"dev\",\n          \"_comment\": \"This memory limit only applies to those gateways whose service does not have an explicitly defined FacadeService. If the service has an explicitly defined FacadeService, then the parameter COMPOSITE_GATEWAY_MEMORY_LIMIT must be passed to this service.\",\n          \"FACADE_GATEWAY_MEMORY_LIMIT\": \"96Mi\"\n        }\n      }\n}'",
    "NC_DIAGNOSTIC_MODE" : "prod"
  },
  "applications" : [ {
    "parameters" : {
      "ACCESS_CONTROL_REMOTE_SETTINGS_ENABLED" : "true",
      "ACCESS_CONTROL_ADMIN_ROLE" : "ROLE_Security_Admin",
      "TEST_PARAM": "test_value"
    },
    "appName" : "Access-Control"
  }, {
    "parameters" : {
      "GW_INGRESS_ANNOTATIONS" : "nginx.ingress.kubernetes.io/proxy-body-size: '400m'\nnginx.ingress.kubernetes.io/proxy-connect-timeout: '2000'\nnginx.ingress.kubernetes.io/proxy-read-timeout: '2000'\nnginx.ingress.kubernetes.io/proxy-send-timeout: '2000'",
      "DBAAS_AGENT_NAMESPACE_ISOLATION_ENABLED" : "false",
      "DEFAULT_TENANT_NAME" : "${tenant.cloud.DEFAULT_TENANT_NAME}",
      "TENANT_LEVEL_ROLES" : "PRODUCT-MANAGER TENANT-ADMIN CUSTOMER-SALES-REPRESENTATIVE CONTENT-MANAGER CUSTOMER-SUPPORT-AGENT GLOBAL-CUSTOMER-SALES-REPRESENTATIVE PORTFOLIO-MANAGER ROLE_READ-ONLY-USER ROLE_CAMPAIGN-AGENT ROLE_CAMPAIGN-MANAGER ROLE_CONTACT-POLICY-MANAGER ROLE_ADMINISTRATOR ROLE_CJM-USER ROLE_CJM-ADMINISTRATOR ROLE_CJM-READ-ONLY-USER ROLE_Security_Admin ROLE_Customer ROLE_CSR ROLE_Salesint_Prod_Admin ROLE_GRAPHQL_USER ROLE_BIS_RO ROLE_BIS_RW ROLE_Cpq_Admin ROLE_Cpq_Product_Sales_Partner ROLE_Cpq_Product_Pre_Sales ROLE_Cpq_Product_Sales_Manager ROLE_Cpq_Product_Director ROLE_Cpq_Product_VP ROLE_Cpq_Product_Commercial_Director ROLE_Cpq_Product_CEO_CFO ROLE_Cpq_Product_Reporting ROLE_Cpq_Product_Anonymous_Customer ROLE_UTM_EXECUTOR ROLE_UTM_SUPERVISOR ROLE_UTM_ADMINISTRATOR ROLE_ORGCHART_ADMINISTRATOR ROLE_ORGCHART_MANAGER ROLE_ORGCHART_TEAM_LEAD ROLE_BC_ADMINISTRATOR ROLE_PIM-ADMIN AM-ADMIN AM-STOCK-USER ROLE_UIM-USER ROLE_cloud-om-ui-read-all ROLE_cloud-om-ui-write-all ROLE_cloud-om-catalog-read-all ROLE_cloud-om-catalog-write-all ROLE_cloud-om-read-product-order ROLE_cloud-om-submit-product-order ROLE_cloud-om-read-service-order ROLE_cloud-om-submit-service-order ROLE_cloud-om-update-order ROLE_cloud-om-read-product-offering-qualification ROLE_cloud-om-submit-product-offering-qualification ROLE_DS_SuperUser ROLE_DS_Sales_Agent ROLE_DS_Sales_Manager ROLE_DS_Administrator ROLE_RTD-READ-ONLY-USER ROLE_RTD-ADMINISTRATOR ROLE_RTC-D-EXT-CLIENT ROLE_CPM_Admin ROLE_cdc_control_superuser ROLE_cdc_control_viewer ROLE_cdc_test_db_superuser ROLE_cdc_control_executor ROLE_cdc_control_importer ROLE_CIP_ADMIN ROLE_BSSCM-ADMIN ROLE_CLOUD-HDS-ADMIN ROLE_CLOUD-HDS-USER ROLE_DPC_USER ROLE_DPC_CONFIGURATOR ROLE_DPC_ADMIN ROLE_RCW-ADMIN ROLE_SCT-ADMIN ROLE_billing-eca-api-access ROLE_CIP_DEV ROLE_CIP_CUSTOMER ROLE_CLOUD-ADMIN ROLE_ID_INTERACTIONS_READ_ONLY_USER ROLE_ID_INTERACTIONS_USER ROLE_ID_DOCUMENTS_READ_ONLY_USER ROLE_ID_DOCUMENTS_USER ROLE_ID_ADMINISTRATOR ROLE_ID_READ_ONLY_USER ROLE_ID_USER ROLE_CDN-ADMIN ROLE_DST-ADMIN ROLE_DST-EXPORT-USER ROLE_DST-EXPORT-ADMIN ROLE_DST-IMPORT-USER ROLE_DFT_USER ROLE_DFT_VIEW ROLE_DFT_ADMIN ROLE_GMS_MOBILE_APP_USER ROLE_DPT_USER ROLE_DPT_ADMIN ROLE_ea_user"
    },
    "appName" : "Cloud-Core"
  }, {
    "parameters" : {
      "KAFKA_CLUSTER_URL" : "${KAFKA_BOOTSTRAP_SERVER}"
    },
    "appName" : "Cloud-Frontend-Platform"
  }, {
    "parameters" : {
      "DICTIONARIES_SECURITY_ROLES" : "ROLE_metamodel-provider-backend,ROLE_metamodel-sample,ROLE_cim-core-service,ROLE_party-interaction-core-service,ROLE_account-mgmt-core,ROLE_payment-method-mgmt-core,ROLE_csrd-fragment-cim-api,ROLE_cpm-core-service,ROLE_external_Cpq_Product_Anonymous_Customer,ROLE_Cpq_Product_Anonymous_Customer,ROLE_TENANT-ADMIN,ROLE_M2M,ROLE_Customer,ROLE_CSR,ROLE_DS_Sales_Agent,ROLE_DS_Sales_Manager,ROLE_DS_SuperUser"
    },
    "appName" : "Core-Extensions"
  }, {
    "parameters" : {
      "ESC_COLLECTOR_PORT" : "1715",
      "ESC_STATIC_HOST" : "${tenant.cloud.CLOUD_ESC_STATIC_HOST}",
      "ESC_COLLECTOR_NS" : "${tenant.cloud.CLOUD_ESC_COLLECTOR_NS}",
      "ESC_STATIC_PORT" : "8080",
      "JAEGER_COLLECTOR_HOST" : "${tenant.cloud.CLOUD_JAEGER_COLLECTOR_HOST}",
      "ZIPKIN_COLLECTOR_HOST" : "${tenant.cloud.CLOUD_JAEGER_COLLECTOR_HOST}",
      "ESC_COLLECTOR_HOST" : "${tenant.cloud.CLOUD_ESC_COLLECTOR_HOST}"
    },
    "appName" : "qs-diagnostic-agent"
  } ]
}
